#version 450

layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;
layout(set = 0, binding = 0) uniform writeonly image2D output_image;

void main()
{
    ivec2 coordinate = ivec2(gl_GlobalInvocationID.xy);
    bool magenta = ((coordinate.x ^ coordinate.y) & 1) == 0;
    imageStore(output_image, coordinate,
        magenta ? vec4(1.0, 0.0, 1.0, 1.0) :
                  vec4(0.0, 1.0, 0.0, 1.0));
}
