#version 450

layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;
layout(set = 0, binding = 0) uniform writeonly image2D output_image;
layout(push_constant) uniform PushConstants {
    vec4 value;
} pc;

void main()
{
    ivec2 coordinate = ivec2(gl_GlobalInvocationID.xy);
    if (all(lessThan(coordinate, imageSize(output_image))))
        imageStore(output_image, coordinate, pc.value);
}
