if(NOT DEFINED INPUT OR NOT DEFINED OUTPUT OR NOT DEFINED SYMBOL)
  message(FATAL_ERROR "INPUT, OUTPUT, and SYMBOL are required")
endif()

file(READ "${INPUT}" spirv_hex HEX)
string(LENGTH "${spirv_hex}" spirv_hex_length)
math(EXPR spirv_remainder "${spirv_hex_length} % 8")
if(NOT spirv_remainder EQUAL 0)
  message(FATAL_ERROR "${INPUT} is not a whole number of SPIR-V words")
endif()

file(WRITE "${OUTPUT}" "#include <stdint.h>\n\nconst uint32_t ${SYMBOL}[] = {\n")
if(spirv_hex_length GREATER 0)
  math(EXPR spirv_last_offset "${spirv_hex_length} - 8")
  foreach(offset RANGE 0 ${spirv_last_offset} 8)
    string(SUBSTRING "${spirv_hex}" ${offset} 2 byte0)
    math(EXPR offset1 "${offset} + 2")
    math(EXPR offset2 "${offset} + 4")
    math(EXPR offset3 "${offset} + 6")
    string(SUBSTRING "${spirv_hex}" ${offset1} 2 byte1)
    string(SUBSTRING "${spirv_hex}" ${offset2} 2 byte2)
    string(SUBSTRING "${spirv_hex}" ${offset3} 2 byte3)
    file(APPEND "${OUTPUT}" "    0x${byte3}${byte2}${byte1}${byte0}u,\n")
  endforeach()
endif()
file(APPEND "${OUTPUT}" "};\n")
